### ISSUE TITLE
Annotations mismatch: Double submitted annotations

### ISSUE THREAD

**Issue by kocmitom** [AppraiseDev/Appraise#10]
I found campaigns that contained annotations done by the same user, with same SegmentID and score, same start date but different end date by several milliseconds. Example:
Campaign: MA20.11.1\ENU_LTH

User | SegmentID | Score | Start | End
englit1f504 | 28 | 61 | 2020-11-06 12:49:02.694000 | 2020-11-06 12:49:10.655000
englit1f504 | 28 | 61 | 2020-11-06 12:49:02.694000 | 2020-11-06 12:49:10.675000

This could possibly happen by a user clicking submit by double-click (some people do this) or by double submission by a bug.

(This bug is possibly related to others I just created: #11 #12)

**Comment by snukky** [comment]
I believe that we haven't seen this bug for a long time now and since then we moved to Azure web service, which could potentially have an impacted here as well. I'll close this issue for the sake of keeping open issues manageable, but please re-open if you experience this again.
