### ISSUE TITLE
Annotations mismatch: User changed their annotation

### ISSUE THREAD

**Issue by kocmitom** [AppraiseDev/Appraise#11]
I found campaigns where there are two annotations for one SegmentID by one user, but different time and different score. TIme suggests that user came back and changed their mind. Example:
Campaign: MA20.10.2\BNB_ENU

User | SegmentID | Score | Start | End
beneng1ef03 | 385 | 64 | 2020-10-26 11:18:22.131000 | 2020-10-26 11:18:46.932000 
beneng1ef03 | 385 | 79 | 2020-10-26 11:19:07.204000 | 2020-10-26 11:19:11.017000

(I have checked that this user didn't do any other annotation in between those two annotations)

(This bug is possibly related to others I just created: #10, #12)

**Comment by snukky** [comment]
I believe that we haven't seen this bug for a long time now and since then we moved to Azure web service, which could potentially have an impacted here as well. I'll close this issue for the sake of keeping open issues manageable, but please re-open if you experience this again.
