### ISSUE TITLE
Using Appraise for crowd-sourced annotation without pre-defined users

### ISSUE THREAD

**Issue by juliafalcao** [AppraiseDev/Appraise#116]
Is it currently possible to use Appraise for a "survey" style of evaluation, that is, without pre-defined users? From what I've seen as I experiment with the tool, it seems that I have to create a certain amount of users and assign them to teams so that they can participate in the campaign, but I might be mistaken. Is there any way I could create a campaign and allow people to then create their own users and participate?

**Comment by snukky** [comment]
I think so. As far as I know the code, it is (or used to be?) possible to create a pool of annotation tasks and users could continue annotations as long as there are tasks in the pool. Unfortunately, I have never used it.

**Comment by juliafalcao** [comment]
> I think so. As far as I know the code, it is (or used to be?) possible to create a pool of annotation tasks and users could continue annotations as long as there are tasks in the pool. Unfortunately, I have never used it.

Thank you for the response! However, I'm still unsure - it seems that, when I create a task, a number of users are created for it. So I guess I would have to assign users to potential participants myself? Is is at all possible to allow users to register themselves on the spot and participate on existing tasks according to availability of tasks for their language(s)?
