### ISSUE TITLE
Annotations mismatch: missing annotations

### ISSUE THREAD

**Issue by kocmitom** [AppraiseDev/Appraise#12]
I found campaigns, where we are missing some annotations for one of the compared systems. Example:
Campaign: MA20.11.1\ENU_CAT

CAND
User | SegmentID
engcat1f505 | 464
engcat1f503 | 467

MSFT
engcat1f505 | 464
engcat1f505 | 466 
engcat1f503 | 467

See that CAND is missing SegmentID 466

This error is very sparse, mostly only 1 missing annotation in a system.

(This bug is possibly related to others I just created: #10, #11)

**Comment by snukky** [comment]
I believe that we haven't seen this bug for a long time now and since then we moved to Azure web service, which could potentially have an impacted here as well. I'll close this issue for the sake of keeping open issues manageable, but please re-open if you experience this again.
