### ISSUE TITLE
MQM/LQM Replace `Mark complete` button with an indicator

### ISSUE THREAD

**Issue by zouharvi** [AppraiseDev/Appraise#135]
The `Mark complete` is another action that is there just for self-management and does not actually send the data. It could be replaced with a label that says `Not done` which disappears after any interaction with the segment.

Suggestion by @kocmitom.

**Comment by zouharvi** [comment]
There is a special handling for the tutorial.

[output.webm](https://github.com/AppraiseDev/Appraise/assets/7661193/03c593fa-c231-4598-9670-ce02afa34d54)

**Comment by zouharvi** [comment]
Resolved in 515d6f4.

**Comment by kocmitom** [comment]
Thank you!
