### ISSUE TITLE
Rework MQM/ESA tutorial

### ISSUE THREAD

**Issue by zouharvi** [AppraiseDev/Appraise#137]
There's feedback that the tutorial is overwhelming. Two suggestions:
- Break it up into two documents
- Pair with instructions "here is the tutorial and afterwards there will be real work"
- Make the instructions super specific (esp. "mark erroneous words")
- Localize tutorials to supported languages or DeEn @kocmitom?
- Add fully correct translation.
- Add `skip tutorial` button

**Comment by kocmitom** [comment]
Localization is low priority for now

**Comment by zouharvi** [comment]
- [x] Break it up into two documents
- [x] Pair with instructions "here is the tutorial and afterwards there will be real work"
- [x] Make the instructions super specific (esp. "mark erroneous words")
- [ ] ~Localize tutorials to supported languages or DeEn @kocmitom?~
- [x] Add fully correct translation.
- [x] Add skip tutorial button
