### ISSUE TITLE
MQM/ESA quality control

### ISSUE THREAD

**Issue by zouharvi** [AppraiseDev/Appraise#141]
- Random corruption of consecutive characters & check error spans
- Incorrect/misplaced translation & check score

@snukky How and when can this be reported to Appraise?

**Comment by zouharvi** [comment]
Add 2 attention checks (see https://github.com/zouharvi/error-span-annotations) that get displayed in the admin console under quality.

![image](https://github.com/AppraiseDev/Appraise/assets/7661193/bfd3153d-b861-4257-8d5d-b5cd61b1b6de)

![image](https://github.com/AppraiseDev/Appraise/assets/7661193/0317ad1b-a6ce-46a8-b688-6921ea990e75)

Resolved in 305354a61a497f4a3f8e9cd3002ff26522769abf.

**Comment by snukky** [comment]
I think we will also need to support our usual QC as in other tasks, which is based on score differences between "TGT" and corresponding "BAD" items, and then reported on the campaign-status page. Maybe we should open a separate issue for this?

**Comment by zouharvi** [comment]
For MQM there is no segment score though. Also the screenshots are of the campaign-status page. Or do you mean something else?

I'm happy to implement things but currently it's very vaguely defined (e.g. what are bad segments and how many of them are there?) and given the schedule, I just went ahead implemented the rudimentary checks of two manually corrupted documents.

**Comment by kocmitom** [comment]
What we do with the BAD segments is that we take an n-gram of words from a segment and replace it with an n-gram of the same length from a different segment. 
But it became an issue that it is too trivial for annotators to discover. At least it is better than randomly scrambled characters which could be ovious even without reading

**Comment by kocmitom** [comment]
A follow up research (not in this iteration) could be to try generating quality control itemsvia LLM.
Basically asking it to update reference in a particular manner ("negate the segment", change the noun for different, remove particular phrase and polish the rest)

**Comment by snukky** [comment]
> For MQM there is no segment score though

We can calculate it on the fly based on their error type/severity weighting.

>  how do we create BAD segments

It's in the WMT batch generation scripts.

> what does score mean for MQM

Not important for QC. BAD refs should have more errors/higher severity, i.e., lower score than TGT, which is all what's needed.

> A follow up research (not in this iteration) could be to try generating quality control itemsvia LLM.

We have had another method for BAD refs generation using contextual LMs, but it has never got to a trail testing.

**Comment by snukky** [comment]
Basically, if you use the WMT batch generation script for generating the batches (I hope we do that), then the only missing part is small update of the `campaign_status` view.

**Comment by zouharvi** [comment]
> Basically, if you use the WMT batch generation script for generating the batches

Unfortunately not at all. There are some details with the MQM/ESA and so I prepare them here: https://github.com/zouharvi/error-span-annotations/blob/main/appraise-preparation/mqm_human_wmt.py

**Comment by snukky** [comment]
Okay, that's fine too. The code for BAD refs generation can be extracted from there and reused too.

**Comment by zouharvi** [comment]
Chaned to dynamic perturbations https://github.com/zouharvi/error-span-annotations/commit/a55f1f7048ce43244fe5c4a81a4f1ccd3b59a843
On Appraise side updated the scoring.
