### ISSUE TITLE
Batches.json always has all quality control items in last documents 

### ISSUE THREAD

**Issue by snukky** [AppraiseDev/Appraise#2]
**Describe the bug**
Batches used in the WMT20 campaign seem to have quality control items (or rather quality control documents) in a task accumulated in the last documents, which makes it possible for annotators to discover the pattern. Documents with quality control items could be distributed randomly in the task.

**To Reproduce**
I think batches for WMT20SrcDocDA have been generated with `create_wmt19_tasks.py`

**Expected behavior**
Documents with quality control items could be distributed randomly in the task.

**Additional context**
Discovered during the WMT20 campaign when one team has reported misaligned documents for en-jp and en-zh accounts.

**Comment by cfedermann** [comment]
Looking into this today.
