### ISSUE TITLE
Help users matching both scores in pairwise tasks 

### ISSUE THREAD

**Issue by snukky** [AppraiseDev/Appraise#23]
**Is your feature request related to a problem? Please describe.**
We would like to minimize the number of pairwise assessments with very small differences between both scores when the user actually wanted to provide the same score but failed bacause of some limitations, like UI, etc. (on smaller screens it might be challenging to get both sliders on exact same positions).

**Describe the solution you'd like**
Two solutions seems reasonable:

1) Add a button "Align sliders" which if clicked, it will set the second slider to the same position as the first slider.
2) Add a checkbox "Synchronize sliders" (or "Dind sliders"?) which if checked, any update of one slider, will change the other slider too. The checkbox should be unchecked at the beginning.

A button should be only visible if there are two different translations.

**Describe alternatives you've considered**
There were other ideas but the two above seem to be the easiest requiring only a few lines of Javascript.

**Comment by snukky** [comment]
@cfedermann, @hitokazm, @kocmitom  Which of the proposed solutions do you prefer? Are you planning to work on that or I can go ahead and implement one quickly?

**Comment by cfedermann** [comment]
Preference for button "Match sliders". Go ahead if you have free cycles, otherwise I can look into this on Friday.
