### ISSUE TITLE
TaskAgenda.reset_taskagenda() does not support data assessment

### ISSUE THREAD

**Issue by cfedermann** [AppraiseDev/Appraise#31]
**Describe the bug**
Our implementation of `TaskAgenda.reset_taskagenda()` does not support `DataAssessmentTask` campaigns.

 # pylint: disable=undefined-variable
    def reset_taskagenda(self):
        """
        Resets annotations and state for this task agenda instance.

        This will do nothing if there are no annotations yet.

        Moves all annotations for the agenda owner to a new user account,
        named as '{self.user.username}-{number:02x}', preserving data for
        future analysis. This user is not added to the respective campaign
        team, so that these annotations will not affect final results.

        The reset moves all related tasks back into self._open_tasks.

        Returns True upon success, False otherwise.
        """
        type_to_result_class_mapping = {
            'DirectAssessmentTask': DirectAssessmentResult,
            'DirectAssessmentContextTask': DirectAssessmentContextResult,
            'DirectAssessmentDocumentTask': DirectAssessmentDocumentResult,
            'MultiModalAssessmentTask': MultiModalAssessmentResult,
            'PairwiseAssessmentTask': PairwiseAssessmentResult,
        }

        result_class = type_to_result_class_mapping.get(
            self.campaign.get_campaign_type(), None
        )

        if not result_class:
            _msg = 'Unknown annotation type {0} for user {1}'.format(
                self.campaign.get_campaign_type(), self.user
            )
            _lvl = messages.ERROR
            return (False, _msg, _lvl)

**Expected behavior**
Resetting a `TaskAgenda` object for a `DataAssessmentTask` campaign should work.

**Comment by snukky** [comment]
This is already fixed in `azure-webapp-dev`: https://github.com/AppraiseDev/Appraise/blob/azure-webapp-dev/EvalData/models/task_agenda.py#L154
